title = "dfe's website"

# The URL the site will be built for
base_url = "https://www.imakestuff.fyi"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Explicitly set default language
default_language = "en"

# Enable taxonomies in default language
taxonomies = [
    { name = "tags" }
]

[languages.de]
# Enable taxonomies in german language
taxonomies = [
    { name = "tags" }
]

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
social_media = [
    { name = "using a modified dose theme", url = "https://github.com/oltdaniel/dose" },
    { name = "github", url = "https://github.com/diflouroethane" },
    { name = "website source", url = "https://github.com/diflouroethane/zola-website"}
]
default_theme = "dark"
