name = "notdose"
description = "an edit of a small blog theme"
license = "MIT"
homepage = "https://github.com/oltdaniel/dose"
min_version = "0.14.0"
# demo = "https://oltdaniel.github.io/dose"

[extra]

[author]
name = "dfe"
homepage = "https://www.imakestuff.fyi"
